import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1A1A1A',
  },
  topSection: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    margin: 0,
    paddingTop: 45,
    padding: 0,
    backgroundColor: '#1A1A1A',
    alignItems: 'center',
    marginTop: 20,
  },
  title: {
    fontSize: 27,
    fontWeight: '700',
    textAlign: 'left',
    color: 'white',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 16,
    color: '#A8A8A8',
    textAlign: 'left',
    fontWeight: 400,
    marginBottom: 20,
  },
  bodySection: {
    flex: 2,
    padding: 20,
    backgroundColor: '#1F1F1F',
  },
  input: {
    borderColor: '#8C8C8C',
    borderWidth: 1,
    borderRadius: 5,
    padding: 10,
    marginBottom: 15,
    height: 50,
    color: 'white',
  },
  button: {
    borderRadius: 5,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  buttonActive: {
    backgroundColor: '#0081F8',
  },
  buttonInactive: {
    backgroundColor: '#252525',
  },
  buttonText: {
    color: '#777777',
    fontWeight: '600',
    fontSize: 16,
  },
  buttonTextActive: {
    color: '#FFFFFF',
  },
  label: {
    color: '#787878',
    marginBottom: 5,
  },
  agreementContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    marginTop: 15,
    marginBottom: 10,
    justifyContent: 'center',
    textAlign: 'center',
    paddingHorizontal: 25,
  },
  agreementText: {
    color: '#909090',
    fontSize: 11,
    textAlign: 'center',
  },
  agreementTextPressable: {
    color: '#909090',
    fontSize: 11,
    textAlign: 'center',
    textDecorationLine: 'underline',
  },
  buttonContainer: {
    borderRadius: 5,
    padding: 0,
    marginTop: 10,
    overflow: 'hidden',
  },
  buttonInner: {
    justifyContent: 'center',
    alignItems: 'center',
    padding: 15,
  },
  switchText: {
    fontSize: 14,
    color: '#A8A8A8',
    marginTop: 20,
    textAlign: 'center',
  },
  switchAction: {
    color: '#0081F8',
    textDecorationLine: 'underline',
  },
  largeAvatar: {
    width: 211,
    height: 211,
    borderRadius: 90,
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    padding: 3,
  },
  avatar: {
    width: 60,
    height: 60,
    borderRadius: 30,
  },
  chooseGalleryButton: {
    borderRadius: 5,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: '#0081F8',
    width: '100%',
  },
  chooseGalleryButtonText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  button2: {
    borderRadius: 5,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    backgroundColor: '#414141',
    width: '100%',
  },
  button2Text: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 16,
  },
  note: {
    color: 'grey',
    fontSize: 12,
    textAlign: 'center',
    marginTop: 20,
    marginBottom: 40,
  },
  orContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 10,
  },
  orDividerLeft: {
    flex: 1,
    height: 2,
    backgroundColor: '#4a4a4a',
    marginRight: 20,
  },
    orDividerRight: {
    flex: 1,
    height: 2,
    backgroundColor: '#4a4a4a',
    marginLeft: 20,
    },
  orText: {
    color: 'grey',
    fontSize: 16,
  },
  avatarWrapper: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
  },
  selectedAvatar: {
    borderWidth: 3,
    borderColor: '#0081F8',
  },
  largeAvatarWrapper: {
    width: 221,
    height: 221,
    borderRadius: 110.5,
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  selectedLargeAvatar: {
    borderWidth: 5,
    borderColor: '#0081F8',
  },
});

export default styles;
